project:
  type: book
  output-dir: _book 

book:
  title: "Bayesian Modelling of Elo Contribution"
  author: "Ali Umair"
  date: "2025-08-13"
  chapters:
    - index.qmd
    - 01-Import.qmd
    - 02-Tidy-Transform.qmd
    - 03-Vizualize.qmd
    - 04-Model.qmd
    - 05-Communicate.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    number-sections: true
    code-fold: true # Add this to allow readers to hide/show code

execute:
  freeze: true
  echo: true
  warning: false